name: Merge to Develop
on:
  push:
    branches:
      - dev
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Format, Lint & Sort code
        uses: ./.github/actions/code_actions
        with:
          node_version: 19
  test:
    runs-on: ubuntu-latest
    needs: [code]
    container:
      image: cypress/browsers:node18.6.0-chrome105-ff104
    strategy:
      fail-fast: false
      matrix:
        screen: [desktop, mobile]
        browser: [chrome]
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Cypress run
        uses: cypress-io/github-action@v5.6.1
        with:
          start: npm run dev
          wait-on: http://localhost:3000/
          # If we have a Mobile screen, set the width & height of the screen
          config: ${{ matrix.screen == 'mobile' && 'viewportWidth=375,viewportHeight=667' }}
          browser: ${{ matrix.browser }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    environment: dev
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Build && Deploy
        uses: ./.github/actions/deploy_actions
        with:
          aws_access_key_id: ${{ secrets.QUANTTRADE_WWW_GHA_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.QUANTTRADE_WWW_GHA_AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          node_version: 19
          s3_bucket: ${{ secrets.QUANTTRADE_WWW_STATIC_HOSTING_BUCKET }}
          cloudfront_distribution_id: ${{ secrets.QUANTTRADE_WWW_CLOUDFRONT_DISTRIBUTION_ID }}
  terraform:
    runs-on: ubuntu-latest
    needs: [deploy]
    environment: dev
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Format, Validate, Plan & Apply Terraform
        uses: ./.github/actions/terraform_actions
        with:
          aws_access_key_id: ${{ secrets.QUANTTRADE_WWW_GHA_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.QUANTTRADE_WWW_GHA_AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          environment: dev